package com.example.datajdbc;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.relational.core.mapping.MappedCollection;
import org.springframework.data.relational.core.mapping.Table;

import java.util.Set;
import java.util.Objects;

@Table("ORDERS")
public class Order {
    private static final long ID_MIN = 1000;
    private static final long ID_MAX = 9999;

    @Id
    private final long orderId;
    private final long customerId;
    @MappedCollection(idColumn = "ORDER_ID")
    private final Set<OrderItem> items;

    public Order(long customerId, Set<OrderItem> items) {
        this.orderId = 0; // The ID will be generated by the database
        this.customerId = customerId;
        validateItems(items);
        this.items = Set.copyOf(items);
    }

    @PersistenceCreator
    private Order(long orderId, long customerId, Set<OrderItem> items) {
        validateId(orderId);
        this.orderId = orderId;
        this.customerId = customerId;
        validateItems(items);
        this.items = Set.copyOf(items);
    }

    private void validateId(long id) {
        if (id < ID_MIN || id > ID_MAX)
            throw new RuntimeException();
    }

    private void validateItems(Set<OrderItem> items) {
        if (items == null || items.isEmpty())
            throw new RuntimeException();
    }

    public long getOrderId() {
        return orderId;
    }

    public long getCustomerId() {
        return customerId;
    }

    public Set<OrderItem> getItems() {
        return Set.copyOf(items);
    }

    @Override
    public int hashCode() {
        return Objects.hash(orderId, customerId, items);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return orderId == order.orderId && customerId == order.customerId && Objects.equals(items, order.items);
    }

    @Override
    public String toString() {
        return "Order{" +
                "orderId=" + orderId +
                ", customerId=" + customerId +
                ", items=" + items +
                '}';
    }
}

