CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID));
ALTER TABLE ORDERS ALTER COLUMN ORDER_ID RESTART WITH 1000;

INSERT INTO ORDERS (CUSTOMER_ID) VALUES (100000000);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, AMOUNT) VALUES (1000, 123123, 10);