CREATE TABLE USERS
(
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    ENABLED  SMALLINT    NOT NULL DEFAULT 0,
    PRIMARY KEY (USERNAME)
);
CREATE TABLE AUTHORITIES
(
    USERNAME  VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS
);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2a$10$HnpBZc.1S3wzVsWTJTvOl.A803fqjK8EjCT9M5sXXsT958pi/.8QK', 1);
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');